matrix:
include:
- language: php
  php:
  - 5.5
  - 5.6
  services:
  - mysql
  before_script:
  - travis_retry composer self_update
  - composer install
  - mysql -u root -e 'CREATE DATABASE d1434995;'
  - mysql -u root -e "CREATE user 's1434994'@'localhost' IDENTIFIED BY 's1434995';"
  - mysql -u root -e "GRANT ALL ON d1434995.*TO 's1434995'@'localhost';"
