 language: php
  php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  services:
  - mysql
  before_script:
  - travis_retry composer self_update
  - composer install --prefer-source --no-interaction --dev
  - mysql -u root -e 'CREATE DATABASE d1434995;'
  - mysql -u root -e "CREATE user 's1434994'@'localhost' IDENTIFIED BY 's1434995';"
  - mysql -u root -e "GRANT ALL ON d1434995.*TO 's1434995'@'localhost';"
  script: phpunit
  matrix:
    allow_features:
      - php: 5.6
      - php: hhvm
     fast_finish: true
     
     on_success: never
     on_failure: always
